/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Estudiantes
 */
public class CalculadoraGráfica extends javax.swing.JFrame {

    int lock=0;
    CalculadoraAritmética calculadora=new CalculadoraAritmética();
    CalculadoraTrigonométrica calculadoraDeTrigo=new CalculadoraTrigonométrica();
    Conversor conversor=new Conversor();
    
    public CalculadoraGráfica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        BotónSiete = new javax.swing.JButton();
        BotónOcho = new javax.swing.JButton();
        BotónNueve = new javax.swing.JButton();
        BotónCuatro = new javax.swing.JButton();
        BotónSeis = new javax.swing.JButton();
        BotónCinco = new javax.swing.JButton();
        BotónUno = new javax.swing.JButton();
        BotónDos = new javax.swing.JButton();
        BotónTres = new javax.swing.JButton();
        BotónPunto = new javax.swing.JButton();
        BotónCero = new javax.swing.JButton();
        Sumar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        Multiplicar = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        Seno = new javax.swing.JButton();
        Tangente = new javax.swing.JButton();
        Secante = new javax.swing.JButton();
        Coseno = new javax.swing.JButton();
        Cotangente = new javax.swing.JButton();
        Cosecante = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        DeleteAll = new javax.swing.JButton();
        Fahlvin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fahlsius = new javax.swing.JButton();
        Kelsius = new javax.swing.JButton();
        Kelvinheit = new javax.swing.JButton();
        Celvin = new javax.swing.JButton();
        Celsiuheit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Gramonzas = new javax.swing.JButton();
        Onzamos = new javax.swing.JButton();
        Grambras = new javax.swing.JButton();
        Libramos = new javax.swing.JButton();
        Kilonadas = new javax.swing.JButton();
        Tonilos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Metries = new javax.swing.JButton();
        Pietros = new javax.swing.JButton();
        Pielgadas = new javax.swing.JButton();
        Pulpies = new javax.swing.JButton();
        CentiAMetros = new javax.swing.JButton();
        MetroACenti = new javax.swing.JButton();
        Metrillas = new javax.swing.JButton();
        Millatros = new javax.swing.JButton();
        Variable = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BotónSiete.setText("7");
        BotónSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónSieteMouseClicked(evt);
            }
        });

        BotónOcho.setText("8");
        BotónOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónOchoMouseClicked(evt);
            }
        });

        BotónNueve.setText("9");
        BotónNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónNueveMouseClicked(evt);
            }
        });

        BotónCuatro.setText("4");
        BotónCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCuatroMouseClicked(evt);
            }
        });

        BotónSeis.setText("6");
        BotónSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónSeisMouseClicked(evt);
            }
        });

        BotónCinco.setText("5");
        BotónCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCincoMouseClicked(evt);
            }
        });

        BotónUno.setText("1");
        BotónUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónUnoMouseClicked(evt);
            }
        });

        BotónDos.setText("2");
        BotónDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónDosMouseClicked(evt);
            }
        });

        BotónTres.setText("3");
        BotónTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónTresMouseClicked(evt);
            }
        });

        BotónPunto.setText(".");
        BotónPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónPuntoMouseClicked(evt);
            }
        });

        BotónCero.setText("0");
        BotónCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCeroMouseClicked(evt);
            }
        });

        Sumar.setText("+");
        Sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarMouseClicked(evt);
            }
        });

        Restar.setText("-");
        Restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarMouseClicked(evt);
            }
        });

        Multiplicar.setText("x");
        Multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplicarMouseClicked(evt);
            }
        });

        Dividir.setText("÷");
        Dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DividirMouseClicked(evt);
            }
        });

        Seno.setText("sen");
        Seno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SenoMouseClicked(evt);
            }
        });

        Tangente.setText("tan");
        Tangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TangenteMouseClicked(evt);
            }
        });

        Secante.setText("sec");
        Secante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecanteMouseClicked(evt);
            }
        });

        Coseno.setText("cos");
        Coseno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosenoMouseClicked(evt);
            }
        });

        Cotangente.setText("cot");
        Cotangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CotangenteMouseClicked(evt);
            }
        });

        Cosecante.setText("csc");
        Cosecante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosecanteMouseClicked(evt);
            }
        });

        Igual.setText("=");
        Igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IgualMouseClicked(evt);
            }
        });
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        DeleteAll.setText("C");
        DeleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteAllMouseClicked(evt);
            }
        });
        DeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllActionPerformed(evt);
            }
        });

        Fahlvin.setText("Fahrenheit a Kelvin");
        Fahlvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FahlvinMouseClicked(evt);
            }
        });

        jLabel1.setText("Temperatura");

        Fahlsius.setText("Fahrenheit a Celsius");
        Fahlsius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FahlsiusMouseClicked(evt);
            }
        });

        Kelsius.setText("Kelvin a Celsius");
        Kelsius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KelsiusMouseClicked(evt);
            }
        });

        Kelvinheit.setText("Kelvin a Fahrenheit");
        Kelvinheit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KelvinheitMouseClicked(evt);
            }
        });

        Celvin.setText("Celsius a Kelvin");
        Celvin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CelvinMouseClicked(evt);
            }
        });

        Celsiuheit.setText("Celsius a Fahrenheit");
        Celsiuheit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CelsiuheitMouseClicked(evt);
            }
        });

        jLabel2.setText("Peso");

        Gramonzas.setText("Gramos a Onzas");
        Gramonzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GramonzasMouseClicked(evt);
            }
        });

        Onzamos.setText("Onzas a Gramos");
        Onzamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnzamosMouseClicked(evt);
            }
        });

        Grambras.setText("Gramos a Libras");
        Grambras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrambrasMouseClicked(evt);
            }
        });

        Libramos.setText("Libras a Gramos");
        Libramos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LibramosMouseClicked(evt);
            }
        });

        Kilonadas.setText("Kilos a Toneladas");
        Kilonadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KilonadasMouseClicked(evt);
            }
        });

        Tonilos.setText("Toneladas a Kilos");
        Tonilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TonilosMouseClicked(evt);
            }
        });

        jLabel3.setText("Longitud");

        Metries.setText("Metros a Pies");
        Metries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetriesMouseClicked(evt);
            }
        });

        Pietros.setText("Pies a Metros");
        Pietros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PietrosMouseClicked(evt);
            }
        });

        Pielgadas.setText("Pies a Pugadas");
        Pielgadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PielgadasMouseClicked(evt);
            }
        });

        Pulpies.setText("Pulgadas a Pies");
        Pulpies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PulpiesMouseClicked(evt);
            }
        });

        CentiAMetros.setText("Centímetros a Metros");
        CentiAMetros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CentiAMetrosMouseClicked(evt);
            }
        });

        MetroACenti.setText("Metros a Centímetros");
        MetroACenti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetroACentiMouseClicked(evt);
            }
        });

        Metrillas.setText("Metros a Millas");
        Metrillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MetrillasMouseClicked(evt);
            }
        });

        Millatros.setText("Millas a Metros");
        Millatros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MillatrosMouseClicked(evt);
            }
        });

        Variable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VariableKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónDos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotónCero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotónTres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Secante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cosecante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Coseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cotangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(Variable))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(Fahlsius, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(Fahlvin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Kelvinheit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Celsiuheit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Kelsius, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Celvin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Onzamos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Libramos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tonilos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Gramonzas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Grambras, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Kilonadas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Metries, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Pielgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CentiAMetros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pietros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Pulpies, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MetroACenti, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Metrillas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Millatros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(378, 378, 378)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Variable, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotónSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Seno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Coseno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotónCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cotangente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotónUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónDos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónTres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Secante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cosecante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotónPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónCero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fahlvin)
                            .addComponent(Kelsius)
                            .addComponent(Celvin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fahlsius)
                            .addComponent(Kelvinheit)
                            .addComponent(Celsiuheit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gramonzas)
                            .addComponent(Grambras)
                            .addComponent(Kilonadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Onzamos)
                            .addComponent(Libramos)
                            .addComponent(Tonilos))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Metries)
                            .addComponent(Pielgadas)
                            .addComponent(CentiAMetros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pietros)
                            .addComponent(Pulpies)
                            .addComponent(MetroACenti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Metrillas)
                            .addComponent(Millatros))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void BotónCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCeroMouseClicked
        
        if(lock==1) {
            Variable.setText("0");
        } else {
            Variable.setText(Variable.getText()+("0"));
        }
    }//GEN-LAST:event_BotónCeroMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Variable.setText("0");
        lock=1;
    }//GEN-LAST:event_formWindowActivated

    private void BotónUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónUnoMouseClicked
        if(lock==1) {
            Variable.setText("1");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("1"));
        }
    }//GEN-LAST:event_BotónUnoMouseClicked

    private void BotónDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónDosMouseClicked
        if(lock==1) {
            Variable.setText("2");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("2"));
        }
    }//GEN-LAST:event_BotónDosMouseClicked

    private void BotónTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónTresMouseClicked
        if(lock==1) {
            Variable.setText("3");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("3"));
        }
    }//GEN-LAST:event_BotónTresMouseClicked

    private void BotónCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCuatroMouseClicked
        if(lock==1) {
            Variable.setText("4");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("4"));
        }
    }//GEN-LAST:event_BotónCuatroMouseClicked

    private void BotónCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCincoMouseClicked
        if(lock==1) {
            Variable.setText("5");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("5"));
        }
    }//GEN-LAST:event_BotónCincoMouseClicked

    private void BotónSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónSeisMouseClicked
        if(lock==1) {
            Variable.setText("6");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("6"));
        }
    }//GEN-LAST:event_BotónSeisMouseClicked

    private void BotónSieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónSieteMouseClicked
        if(lock==1) {
            Variable.setText("7");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("7"));
        }
    }//GEN-LAST:event_BotónSieteMouseClicked

    private void BotónOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónOchoMouseClicked
        if(lock==1) {
            Variable.setText("8");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("8"));
        }
    }//GEN-LAST:event_BotónOchoMouseClicked

    private void BotónNueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónNueveMouseClicked
        if(lock==1) {
            Variable.setText("9");
            lock=0;
        } else {
            Variable.setText(Variable.getText()+("9"));
        }
    }//GEN-LAST:event_BotónNueveMouseClicked

    private void BotónPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónPuntoMouseClicked
        if(Double.parseDouble(Variable.getText())-Integer.parseInt(Variable.getText())==0){
            Variable.setText(Variable.getText()+("."));
        }
        lock=0;
    }//GEN-LAST:event_BotónPuntoMouseClicked

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IgualActionPerformed

    private void DeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllActionPerformed
        
    }//GEN-LAST:event_DeleteAllActionPerformed

    private void DeleteAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAllMouseClicked
        Variable.setText("0");
        calculadora.operador=0;
        lock=1;
    }//GEN-LAST:event_DeleteAllMouseClicked

    private void SenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenoMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularSeno()));
        lock=1;
    }//GEN-LAST:event_SenoMouseClicked

    private void CosenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosenoMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCoseno()));
        lock=1;
    }//GEN-LAST:event_CosenoMouseClicked

    private void TangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TangenteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularTangente()));
        lock=1;
    }//GEN-LAST:event_TangenteMouseClicked

    private void CotangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotangenteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCotangente()));
        lock=1;
    }//GEN-LAST:event_CotangenteMouseClicked

    private void SecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecanteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularSecante()));
        lock=1;
    }//GEN-LAST:event_SecanteMouseClicked

    private void CosecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosecanteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCosecante()));
        lock=1;
    }//GEN-LAST:event_CosecanteMouseClicked

    private void SumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarMouseClicked
        calculadora.operador=1;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        lock=1;
    }//GEN-LAST:event_SumarMouseClicked

    private void RestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarMouseClicked
        calculadora.operador=2;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        lock=1;
    }//GEN-LAST:event_RestarMouseClicked

    private void MultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicarMouseClicked
        calculadora.operador=3;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        lock=1;
    }//GEN-LAST:event_MultiplicarMouseClicked

    private void DividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DividirMouseClicked
        calculadora.operador=4;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        lock=1;
    }//GEN-LAST:event_DividirMouseClicked

    private void IgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IgualMouseClicked
        calculadora.operando2=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadora.operar()));
        lock=1;
    }//GEN-LAST:event_IgualMouseClicked

    private void FahlvinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FahlvinMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.fahrenheitToKelvin()));
        lock=1;
    }//GEN-LAST:event_FahlvinMouseClicked

    private void FahlsiusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FahlsiusMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.fahrenheitToCelsius()));
        lock=1;
    }//GEN-LAST:event_FahlsiusMouseClicked

    private void KelsiusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KelsiusMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.kelvinToCelsius()));
        lock=1;
    }//GEN-LAST:event_KelsiusMouseClicked

    private void KelvinheitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KelvinheitMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.kelvinToFahrenheit()));
        lock=1;
    }//GEN-LAST:event_KelvinheitMouseClicked

    private void CelvinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelvinMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.celsiusToKelvin()));
        lock=1;
    }//GEN-LAST:event_CelvinMouseClicked

    private void CelsiuheitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelsiuheitMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.celsiusToFahrenheit()));
        lock=1;
    }//GEN-LAST:event_CelsiuheitMouseClicked

    private void GramonzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GramonzasMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.gramToOunce()));
        lock=1;
    }//GEN-LAST:event_GramonzasMouseClicked

    private void OnzamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnzamosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.ounceToGram()));
        lock=1;
    }//GEN-LAST:event_OnzamosMouseClicked

    private void GrambrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrambrasMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.gramToPound()));
        lock=1;
    }//GEN-LAST:event_GrambrasMouseClicked

    private void LibramosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LibramosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.poundToGram()));
        lock=1;
    }//GEN-LAST:event_LibramosMouseClicked

    private void KilonadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KilonadasMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.kilogramToTonneAndGtK()));
        lock=1;
    }//GEN-LAST:event_KilonadasMouseClicked

    private void TonilosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TonilosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.tonneToKilogramAndKtG()));
        lock=1;
    }//GEN-LAST:event_TonilosMouseClicked

    private void MetriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetriesMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.metresToFeet()));
        lock=1;
    }//GEN-LAST:event_MetriesMouseClicked

    private void PietrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PietrosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.feetToMetres()));
        lock=1;
    }//GEN-LAST:event_PietrosMouseClicked

    private void PielgadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PielgadasMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.feetToInches()));
        lock=1;
    }//GEN-LAST:event_PielgadasMouseClicked

    private void PulpiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PulpiesMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.inchesToFeet()));
        lock=1;
    }//GEN-LAST:event_PulpiesMouseClicked

    private void CentiAMetrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CentiAMetrosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.centimetresToMetres()));
        lock=1;
    }//GEN-LAST:event_CentiAMetrosMouseClicked

    private void MetroACentiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetroACentiMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.metresToCentimetres()));
        lock=1;
    }//GEN-LAST:event_MetroACentiMouseClicked

    private void MetrillasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetrillasMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.metresToMiles()));
        lock=1;
    }//GEN-LAST:event_MetrillasMouseClicked

    private void MillatrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MillatrosMouseClicked
        conversor.unidades=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(conversor.milesToMetres()));
        lock=1;
    }//GEN-LAST:event_MillatrosMouseClicked

    private void VariableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VariableKeyTyped
        char tecla = evt.getKeyChar();
        if(((tecla<'0')||(tecla>'9'))&&(tecla!='.')){
            evt.consume();
        }
        if(tecla=='.'){
            if(Double.parseDouble(Variable.getText())-Integer.parseInt(Variable.getText())!=0){
                evt.consume();
            }
        }
    }//GEN-LAST:event_VariableKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculadoraGráfica().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónCero;
    private javax.swing.JButton BotónCinco;
    private javax.swing.JButton BotónCuatro;
    private javax.swing.JButton BotónDos;
    private javax.swing.JButton BotónNueve;
    private javax.swing.JButton BotónOcho;
    private javax.swing.JButton BotónPunto;
    private javax.swing.JButton BotónSeis;
    private javax.swing.JButton BotónSiete;
    private javax.swing.JButton BotónTres;
    private javax.swing.JButton BotónUno;
    private javax.swing.JButton Celsiuheit;
    private javax.swing.JButton Celvin;
    private javax.swing.JButton CentiAMetros;
    private javax.swing.JButton Cosecante;
    private javax.swing.JButton Coseno;
    private javax.swing.JButton Cotangente;
    private javax.swing.JButton DeleteAll;
    private javax.swing.JButton Dividir;
    private javax.swing.JButton Fahlsius;
    private javax.swing.JButton Fahlvin;
    private javax.swing.JButton Grambras;
    private javax.swing.JButton Gramonzas;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Kelsius;
    private javax.swing.JButton Kelvinheit;
    private javax.swing.JButton Kilonadas;
    private javax.swing.JButton Libramos;
    private javax.swing.JButton Metries;
    private javax.swing.JButton Metrillas;
    private javax.swing.JButton MetroACenti;
    private javax.swing.JButton Millatros;
    private javax.swing.JButton Multiplicar;
    private javax.swing.JButton Onzamos;
    private javax.swing.JButton Pielgadas;
    private javax.swing.JButton Pietros;
    private javax.swing.JButton Pulpies;
    private javax.swing.JButton Restar;
    private javax.swing.JButton Secante;
    private javax.swing.JButton Seno;
    private javax.swing.JButton Sumar;
    private javax.swing.JButton Tangente;
    private javax.swing.JButton Tonilos;
    private javax.swing.JTextField Variable;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
