/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Estudiantes
 */
public class CalculadoraGráfica extends javax.swing.JFrame {

    int operador;
    CalculadoraAritmética calculadora=new CalculadoraAritmética();
    CalculadoraTrigonométrica calculadoraDeTrigo=new CalculadoraTrigonométrica();
    
    public CalculadoraGráfica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        BotónSiete = new javax.swing.JButton();
        BotónOcho = new javax.swing.JButton();
        BotónNueve = new javax.swing.JButton();
        BotónCuatro = new javax.swing.JButton();
        BotónSeis = new javax.swing.JButton();
        BotónCinco = new javax.swing.JButton();
        BotónUno = new javax.swing.JButton();
        BotónDos = new javax.swing.JButton();
        BotónTres = new javax.swing.JButton();
        BotónPunto = new javax.swing.JButton();
        BotónCero = new javax.swing.JButton();
        Sumar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        Multiplicar = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        Seno = new javax.swing.JButton();
        Tangente = new javax.swing.JButton();
        Secante = new javax.swing.JButton();
        Coseno = new javax.swing.JButton();
        Cotangente = new javax.swing.JButton();
        Cosecante = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        DeleteAll = new javax.swing.JButton();
        Variable = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BotónSiete.setText("7");
        BotónSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónSieteMouseClicked(evt);
            }
        });

        BotónOcho.setText("8");
        BotónOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónOchoMouseClicked(evt);
            }
        });

        BotónNueve.setText("9");
        BotónNueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónNueveMouseClicked(evt);
            }
        });

        BotónCuatro.setText("4");
        BotónCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCuatroMouseClicked(evt);
            }
        });

        BotónSeis.setText("6");
        BotónSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónSeisMouseClicked(evt);
            }
        });

        BotónCinco.setText("5");
        BotónCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCincoMouseClicked(evt);
            }
        });

        BotónUno.setText("1");
        BotónUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónUnoMouseClicked(evt);
            }
        });

        BotónDos.setText("2");
        BotónDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónDosMouseClicked(evt);
            }
        });

        BotónTres.setText("3");
        BotónTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónTresMouseClicked(evt);
            }
        });

        BotónPunto.setText(".");
        BotónPunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónPuntoMouseClicked(evt);
            }
        });

        BotónCero.setText("0");
        BotónCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotónCeroMouseClicked(evt);
            }
        });

        Sumar.setText("+");
        Sumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumarMouseClicked(evt);
            }
        });

        Restar.setText("-");
        Restar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RestarMouseClicked(evt);
            }
        });

        Multiplicar.setText("x");
        Multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplicarMouseClicked(evt);
            }
        });

        Dividir.setText("÷");
        Dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DividirMouseClicked(evt);
            }
        });

        Seno.setText("sen");
        Seno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SenoMouseClicked(evt);
            }
        });

        Tangente.setText("tan");
        Tangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TangenteMouseClicked(evt);
            }
        });

        Secante.setText("sec");
        Secante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SecanteMouseClicked(evt);
            }
        });

        Coseno.setText("cos");
        Coseno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosenoMouseClicked(evt);
            }
        });

        Cotangente.setText("cot");
        Cotangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CotangenteMouseClicked(evt);
            }
        });

        Cosecante.setText("csc");
        Cosecante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CosecanteMouseClicked(evt);
            }
        });

        Igual.setText("=");
        Igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IgualMouseClicked(evt);
            }
        });
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        DeleteAll.setText("C");
        DeleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteAllMouseClicked(evt);
            }
        });
        DeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllActionPerformed(evt);
            }
        });

        Variable.setBackground(new java.awt.Color(255, 0, 0));
        Variable.setFont(new java.awt.Font("Info Book", 0, 36)); // NOI18N
        Variable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Variable.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Variable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónDos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BotónCero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotónTres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotónPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Secante))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cosecante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotónSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotónNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Seno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(Coseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cotangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Variable, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotónSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Coseno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotónCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tangente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cotangente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotónUno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónDos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónTres, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Secante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cosecante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotónPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotónCero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void BotónCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCeroMouseClicked
        
        if("0".equals(Variable.getText())) {
            Variable.setText("0");
        } else {
            Variable.setText(Variable.getText()+("0"));
        }
    }//GEN-LAST:event_BotónCeroMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Variable.setText("0");
        
    }//GEN-LAST:event_formWindowActivated

    private void BotónUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónUnoMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("1");
        } else {
            Variable.setText(Variable.getText()+("1"));
        }
    }//GEN-LAST:event_BotónUnoMouseClicked

    private void BotónDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónDosMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("2");
        } else {
            Variable.setText(Variable.getText()+("2"));
        }
    }//GEN-LAST:event_BotónDosMouseClicked

    private void BotónTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónTresMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("3");
        } else {
            Variable.setText(Variable.getText()+("3"));
        }
    }//GEN-LAST:event_BotónTresMouseClicked

    private void BotónCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCuatroMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("4");
        } else {
            Variable.setText(Variable.getText()+("4"));
        }
    }//GEN-LAST:event_BotónCuatroMouseClicked

    private void BotónCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónCincoMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("5");
        } else {
            Variable.setText(Variable.getText()+("5"));
        }
    }//GEN-LAST:event_BotónCincoMouseClicked

    private void BotónSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónSeisMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("6");
        } else {
            Variable.setText(Variable.getText()+("6"));
        }
    }//GEN-LAST:event_BotónSeisMouseClicked

    private void BotónSieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónSieteMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("7");
        } else {
            Variable.setText(Variable.getText()+("7"));
        }
    }//GEN-LAST:event_BotónSieteMouseClicked

    private void BotónOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónOchoMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("8");
        } else {
            Variable.setText(Variable.getText()+("8"));
        }
    }//GEN-LAST:event_BotónOchoMouseClicked

    private void BotónNueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónNueveMouseClicked
        if("0".equals(Variable.getText())) {
            Variable.setText("9");
        } else {
            Variable.setText(Variable.getText()+("9"));
        }
    }//GEN-LAST:event_BotónNueveMouseClicked

    private void BotónPuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotónPuntoMouseClicked
        Variable.setText(Variable.getText()+("."));
    }//GEN-LAST:event_BotónPuntoMouseClicked

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IgualActionPerformed

    private void DeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllActionPerformed
        
    }//GEN-LAST:event_DeleteAllActionPerformed

    private void DeleteAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteAllMouseClicked
        Variable.setText("0");
    }//GEN-LAST:event_DeleteAllMouseClicked

    private void SenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SenoMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularSeno()));
    }//GEN-LAST:event_SenoMouseClicked

    private void CosenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosenoMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCoseno()));
    }//GEN-LAST:event_CosenoMouseClicked

    private void TangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TangenteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularTangente()));
    }//GEN-LAST:event_TangenteMouseClicked

    private void CotangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CotangenteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCotangente()));
    }//GEN-LAST:event_CotangenteMouseClicked

    private void SecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SecanteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularSecante()));
    }//GEN-LAST:event_SecanteMouseClicked

    private void CosecanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CosecanteMouseClicked
        calculadoraDeTrigo.ángulo=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadoraDeTrigo.calcularCosecante()));
    }//GEN-LAST:event_CosecanteMouseClicked

    private void SumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumarMouseClicked
        calculadora.operador=1;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        Variable.setText("0");
    }//GEN-LAST:event_SumarMouseClicked

    private void RestarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RestarMouseClicked
        calculadora.operador=2;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        Variable.setText("0");
    }//GEN-LAST:event_RestarMouseClicked

    private void MultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplicarMouseClicked
        calculadora.operador=3;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        Variable.setText("0");
    }//GEN-LAST:event_MultiplicarMouseClicked

    private void DividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DividirMouseClicked
        calculadora.operador=4;
        calculadora.operando1=Double.parseDouble(Variable.getText());
        Variable.setText("0");
    }//GEN-LAST:event_DividirMouseClicked

    private void IgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IgualMouseClicked
        calculadora.operando2=Double.parseDouble(Variable.getText());
        Variable.setText(String.valueOf(calculadora.operar()));
    }//GEN-LAST:event_IgualMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGráfica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónCero;
    private javax.swing.JButton BotónCinco;
    private javax.swing.JButton BotónCuatro;
    private javax.swing.JButton BotónDos;
    private javax.swing.JButton BotónNueve;
    private javax.swing.JButton BotónOcho;
    private javax.swing.JButton BotónPunto;
    private javax.swing.JButton BotónSeis;
    private javax.swing.JButton BotónSiete;
    private javax.swing.JButton BotónTres;
    private javax.swing.JButton BotónUno;
    private javax.swing.JButton Cosecante;
    private javax.swing.JButton Coseno;
    private javax.swing.JButton Cotangente;
    private javax.swing.JButton DeleteAll;
    private javax.swing.JButton Dividir;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multiplicar;
    private javax.swing.JButton Restar;
    private javax.swing.JButton Secante;
    private javax.swing.JButton Seno;
    private javax.swing.JButton Sumar;
    private javax.swing.JButton Tangente;
    private javax.swing.JLabel Variable;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
